'use strict';
/* Bekannte Marken und Warennamen je Produktgruppe (eigene Zusammenstellung), damit man Favoriten auch für Marken
   anlegen kann, die noch in keinem Prospekt vorkamen. Schlüssel: "Kategorie|Produktgruppe" wie in den Angeboten.
   Treffer: Markenschlüssel des Angebots oder der Name als ganze Wortfolge im Titel (z.B. „Mars Twix“ -> Twix). */
const KNOWN_BRANDS = {
  // Fleisch, Wurst, Fisch
  'Fleisch & Geflügel|Hähnchen': 'Wiesenhof, Gutfried, Heidemark, Stolle',
  'Fleisch & Geflügel|Pute': 'Wiesenhof, Gutfried, Heidemark',
  'Fleisch & Geflügel|Burger & Frikadellen': 'Meica, Garden Gourmet, Like Meat, Rügenwalder Mühle, Beyond Meat',
  'Wurst & Aufschnitt|Bratwurst': 'Meica, Rügenwalder Mühle, Wiltmann, Nürnberger, Thüringer',
  'Wurst & Aufschnitt|Würstchen': 'Meica, Böklunder, Herta, Rügenwalder Mühle, Wiesenhof, Gutfried',
  'Wurst & Aufschnitt|Salami': 'Böklunder, Gutfried, Herta, Wiltmann, Stockmeyer, Houdek, Rügenwalder Mühle, Ponnath',
  'Wurst & Aufschnitt|Schinken': 'Abraham, Herta, Gutfried, Rügenwalder Mühle, Stockmeyer, Houdek, Dulano',
  'Wurst & Aufschnitt|Streichwurst & Pastete': 'Rügenwalder Mühle, Henaff, Gutfried, Stockmeyer',
  'Wurst & Aufschnitt|Aufschnitt': 'Gutfried, Herta, Rügenwalder Mühle, Böklunder, Wiesenhof, Stockmeyer, Zimmermann',
  'Fisch & Meeresfrüchte|Lachs': 'Deutsche See, Gottfried Friedrichs, Almare, Iglo',
  'Fisch & Meeresfrüchte|Thunfisch': 'Saupiquet, Rio Mare, Hawesta, Followfish',
  'Fisch & Meeresfrüchte|Hering & Matjes': 'Hawesta, Appel, Rügenfisch, Homann, Ostsee Fisch',
  'Fisch & Meeresfrüchte|Räucherfisch': 'Gottfried Friedrichs, Deutsche See',

  // Molkerei & Käse
  'Milch & Molkerei|Butter': 'Kerrygold, Meggle, Weihenstephan, Landliebe, Kerrygold, Arla',
  'Milch & Molkerei|Margarine & Streichfett': 'Rama, Lätta, Deli Reform, Becel, Sanella, Kerrygold',
  'Milch & Molkerei|Pflanzendrinks': 'Alpro, Oatly, Provamel, Innocent',
  'Milch & Molkerei|Milchgetränke': 'Müllermilch, Weihenstephan, Nesquik, Starbucks, Emmi',
  'Milch & Molkerei|Milch': 'Weihenstephan, Landliebe, Bärenmarke, Arla, Berchtesgadener Land, Schwarzwaldmilch, Hansano',
  'Milch & Molkerei|Joghurt': 'Müller, Ehrmann, Danone, Zott, Weihenstephan, Landliebe, Almighurt, Activia, Alpro, Andechser',
  'Milch & Molkerei|Quark & Skyr': 'Exquisa, Ehrmann, Arla, Milsani, Skyr, Weihenstephan',
  'Milch & Molkerei|Sahne & Schmand': 'Weihenstephan, Bärenmarke, Meggle, Schwarzwaldmilch',
  'Milch & Molkerei|Pudding & Desserts': 'Dr. Oetker, Paula, Müller, Zott, Ehrmann, Danone, Monte, Grand Dessert',
  'Käse|Frischkäse': 'Philadelphia, Exquisa, Bresso, Miree, Buko, Almette',
  'Käse|Mozzarella & Burrata': 'Galbani, Zott, Züger, Santa Lucia',
  'Käse|Feta & Hirtenkäse': 'Salakis, Patros, Dodoni, Apetina',
  'Käse|Weichkäse': 'Bergader, Géramont, Président, Rougette, Milkana, Saint Albray',
  'Käse|Reibekäse': 'Milram, Grünländer, Galbani',
  'Käse|Hartkäse & Parmesan': 'Grana Padano, Parmigiano Reggiano, Galbani',
  'Käse|Käsescheiben': 'Leerdammer, Milram, Grünländer, Gouda, Hochland, Bergader',
  'Käse|Schnittkäse': 'Leerdammer, Milram, Grünländer, Bergader, Old Amsterdam, Maasdamer',
  'Käse|Grill- & Ofenkäse': 'Rougette, Hochland, Patros',

  // Brot, Tiefkühl
  'Brot & Backwaren|Toast': 'Golden Toast, Harry, Lieken Urkorn',
  'Brot & Backwaren|Brot': 'Harry, Lieken Urkorn, Mestemacher, Golden Toast, Pema',
  'Brot & Backwaren|Kuchen & Gebäck': 'Coppenrath & Wiese, Kuchenmeister, Dr. Oetker',
  'Tiefkühl|Pizza & Baguettes': 'Dr. Oetker, Ristorante, Wagner, Die Ofenfrische, Big City, Gustavo Gusto, Casa Romantica, Alberto',
  'Tiefkühl|Eis': 'Langnese, Magnum, Cornetto, Ben & Jerry\'s, Häagen-Dazs, Mövenpick, Nestlé Schöller, Carte d\'Or, Nogger',
  'Tiefkühl|Pommes & Kartoffelprodukte': 'McCain, Agrarfrost, Frosta',
  'Tiefkühl|TK-Fisch': 'Iglo, Frosta, Costa, Käpt\'n Iglo',
  'Tiefkühl|TK-Gemüse': 'Iglo, Frosta, Bonduelle',
  'Tiefkühl|TK-Fertiggerichte': 'Frosta, Iglo, Bofrost, Wagner',
  'Tiefkühl|TK-Kuchen & Backwaren': 'Coppenrath & Wiese, Dr. Oetker',

  // Vorrat
  'Vorrat & Konserven|Nudeln': 'Barilla, Buitoni, Birkel, 3 Glocken, De Cecco, Rana, Bernbacher',
  'Vorrat & Konserven|Reis & Getreide': 'Uncle Ben\'s, Ben\'s Original, Oryza, Reis-Fit, Müller\'s Mühle',
  'Vorrat & Konserven|Öl & Essig': 'Bertolli, Mazola, Thomy, Brändle, Kühne, Hengstenberg, Rapso',
  'Vorrat & Konserven|Mehl, Zucker & Backen': 'Aurora, Diamant, Südzucker, Dr. Oetker, Kathreiner, Mondamin',
  'Vorrat & Konserven|Ketchup, Senf & Mayo': 'Heinz, Hela, Kühne, Develey, Thomy, Händlmaier, Löwensenf, Bautz\'ner',
  'Vorrat & Konserven|Soßen & Pesto': 'Knorr, Maggi, Barilla, Miracoli, Bertolli, Mondamin, Uncle Ben\'s',
  'Vorrat & Konserven|Suppen & Eintöpfe': 'Erasco, Maggi, Knorr, Sonnen Bassermann, Lacroix',
  'Vorrat & Konserven|Fertiggerichte': 'Maggi, Knorr, Erasco, Miracoli, Sonnen Bassermann, 5 Minuten Terrine',
  'Vorrat & Konserven|Gemüse- & Obstkonserven': 'Bonduelle, Hengstenberg, Kühne, Del Monte, Libby\'s, Garten Gold',
  'Vorrat & Konserven|Gewürze': 'Ostmann, Fuchs, Maggi, Knorr, Kotányi',

  // Frühstück
  'Frühstück & Aufstrich|Müsli & Cerealien': 'Kellogg\'s, Nestlé, Kölln, Seitenbacher, Dr. Oetker Vitalis, Nesquik, Cini Minis, Lion, Chocapic',
  'Frühstück & Aufstrich|Haferflocken & Porridge': 'Kölln, Seitenbacher, Ja!',
  'Frühstück & Aufstrich|Nuss-Nougat-Creme': 'Nutella, Nudossi, Nusspli',
  'Frühstück & Aufstrich|Honig': 'Langnese, Breitsamer',
  'Frühstück & Aufstrich|Konfitüre & Fruchtaufstrich': 'Schwartau, Zentis, Mövenpick, Bonne Maman, Göbber',

  // Süßes & Snacks
  'Süßes & Snacks|Chips & Knabbereien': 'Chio, Funny-frisch, Lay\'s, Pringles, Crunchips, Pom-Bär, Lorenz, Saltletts, Erdnussflips',
  'Süßes & Snacks|Nüsse & Trockenfrüchte': 'Ültje, Seeberger, Kluth, Farmer\'s Snack',
  'Süßes & Snacks|Fruchtgummi & Bonbons': 'Haribo, Katjes, Trolli, Nimm2, Werther\'s, Maoam, Mentos, Ricola, Em-eukal, Storck',
  'Süßes & Snacks|Pralinen': 'Ferrero Rocher, Raffaello, Mon Chéri, Lindt, Merci, Toffifee, Celebrations, Lindor, After Eight',
  'Süßes & Snacks|Riegel': 'Mars, Snickers, Twix, Bounty, Milky Way, KitKat, Lion, Balisto, Duplo, Hanuta, Kinder Riegel, '
    + 'Kinder Bueno, Knoppers, Corny, Nuts, Yogurette, Mr. Tom, Pickup',
  'Süßes & Snacks|Kekse & Waffeln': 'Bahlsen, Leibniz, Prinzen Rolle, Oreo, Pick Up, Hanuta, Manner, Choco Leibniz, Lambertz, Brandt',
  'Süßes & Snacks|Schokolade': 'Milka, Ritter Sport, Lindt, Kinder, Ferrero, Toblerone, Merci, Sarotti, Hachez, Nestlé, Schogetten, Trumpf',
  'Süßes & Snacks|Weihnachtssüßes': 'Lambertz, Milka, Lindt, Kinder, Ferrero, Riegelein',

  // Kaffee & Tee
  'Kaffee & Tee|Kapseln & Pads': 'Nescafé Dolce Gusto, Nespresso, Tassimo, Senseo, Jacobs, L\'OR, Starbucks, Lavazza',
  'Kaffee & Tee|Instant & Cappuccino': 'Nescafé, Jacobs, Krüger, Cafet',
  'Kaffee & Tee|Kaffee (Bohnen)': 'Tchibo, Jacobs, Lavazza, Dallmayr, Melitta, Segafredo, Eduscho, Mövenpick, Illy',
  'Kaffee & Tee|Kaffee (gemahlen)': 'Jacobs, Tchibo, Dallmayr, Melitta, Onko, Eduscho, Idee Kaffee, Lavazza, Mövenpick',
  'Kaffee & Tee|Tee': 'Teekanne, Meßmer, Lipton, Pompadour, Yogi Tea, Milford, OnnO',
  'Kaffee & Tee|Kakao': 'Kaba, Nesquik, Suchard Express, Ovomaltine',

  // Getränke
  'Getränke|Wasser': 'Gerolsteiner, Vittel, Volvic, Adelholzener, Apollinaris, Bad Brambacher, Rheinfels Quelle, Christinen, Staatl. Fachingen, Überkinger',
  'Getränke|Energy Drinks': 'Red Bull, Monster, Rockstar, Effect, Relentless',
  'Getränke|Eistee': 'Lipton, Pfanner, Arizona, Fuze Tea, Nestea',
  'Getränke|Cola': 'Coca-Cola, Pepsi, Fritz-Kola, Afri Cola, Club-Mate, Sinalco',
  'Getränke|Limonade & Schorle': 'Fanta, Sprite, Mezzo Mix, Schweppes, Bionade, Lipton, Sinalco, Capri-Sun, Lift, Punica',
  'Getränke|Saft & Nektar': 'Hohes C, Granini, Valensina, Rauch, Amecke, Innocent, Punica, Pfanner, Albi',
  'Getränke|Sirup': 'Teekanne, Monin, Sodastream',

  // Bier, Wein, Spirituosen
  'Bier|Pils': 'Krombacher, Warsteiner, Veltins, Bitburger, Beck\'s, Jever, Radeberger, Hasseröder, Holsten, Flensburger, Herforder, Diebels',
  'Bier|Alkoholfreies Bier': 'Krombacher, Erdinger, Beck\'s, Clausthaler, Warsteiner, Bitburger, Veltins',
  'Bier|Radler & Biermix': 'Krombacher, Veltins, Warsteiner, Beck\'s, Mixery, Karlsberg',
  'Bier|Weizenbier': 'Erdinger, Paulaner, Franziskaner, Schöfferhofer, Maisel\'s, Weihenstephaner',
  'Bier|Spezialbier': 'Paulaner, Augustiner, Diebels, Köstritzer',
  'Wein & Sekt|Sekt & Prosecco': 'Rotkäppchen, Mumm, Freixenet, Henkell, Kupferberg, Söhnlein, Fürst von Metternich',
  'Wein & Sekt|Glühwein': 'Gerstacker, Nürnberger',
  'Spirituosen|Whisky': 'Jack Daniel\'s, Jameson, Johnnie Walker, Ballantine\'s, Jim Beam, Glenfiddich, Tullamore Dew, Chivas',
  'Spirituosen|Wodka': 'Absolut, Smirnoff, Gorbatschow, Puschkin',
  'Spirituosen|Rum': 'Bacardi, Havana Club, Captain Morgan, Pott',
  'Spirituosen|Gin': 'Gordon\'s, Bombay Sapphire, Tanqueray, Hendrick\'s',
  'Spirituosen|Aperitif': 'Aperol, Campari, Martini, Lillet',
  'Spirituosen|Likör': 'Jägermeister, Baileys, Kleiner Feigling, Ramazzotti, Averna',
  'Spirituosen|Weinbrand & Cognac': 'Asbach, Mariacron, Chantré, Hennessy',
  'Spirituosen|Korn & Klare': 'Berentzen, Doornkaat, Nordhäuser',

  // Drogerie, Baby
  'Drogerie & Pflege|Duschen & Baden': 'Duschdas, Axe, Nivea, Dove, Fa, Palmolive, Adidas, Balea, CD, Kneipp, Tetesept',
  'Drogerie & Pflege|Haarpflege': 'Schauma, Pantene, Head & Shoulders, Garnier Fructis, Elvital, Gliss Kur, Syoss, Guhl, Nivea',
  'Drogerie & Pflege|Haarfarbe': 'Poly Color, Garnier, Schwarzkopf, Syoss, L\'Oréal',
  'Drogerie & Pflege|Zahnpflege': 'Colgate, Signal, Elmex, Oral-B, Blend-a-med, Odol, Sensodyne, Meridol, Dentagard',
  'Drogerie & Pflege|Deo': 'Rexona, Nivea, Axe, Dove, Fa, 8x4, Adidas, Old Spice',
  'Drogerie & Pflege|Rasur': 'Gillette, Wilkinson, Nivea Men, Venus',
  'Drogerie & Pflege|Gesichtspflege & Make-up': 'Nivea, Garnier, L\'Oréal, Maybelline, Bebe, Neutrogena',
  'Drogerie & Pflege|Körperpflege': 'Nivea, Dove, Penaten, Bebe, Kneipp, Eucerin',
  'Drogerie & Pflege|Hygiene': 'Always, O.B., Tempo, Kleenex, Zewa, Carefree',
  'Drogerie & Pflege|Gesundheit & Vitamine': 'Doppelherz, Abtei, Orthomol, Centrum',
  'Baby & Kind|Windeln': 'Pampers, Huggies, Babylove',
  'Baby & Kind|Feuchttücher': 'Pampers, Penaten, Bebe',
  'Baby & Kind|Babynahrung': 'Hipp, Alete, Milupa, Aptamil, Bebivita',

  // Haushalt
  'Haushalt & Reinigung|Waschmittel': 'Persil, Ariel, Weißer Riese, Spee, Lenor, Coral, Perwoll, Sunil, Omo',
  'Haushalt & Reinigung|Weichspüler & Wäschepflege': 'Lenor, Kuschelweich, Vernel, Silan, Dr. Beckmann, Vanish, Perwoll',
  'Haushalt & Reinigung|Geschirrspülen': 'Fairy, Pril, Finish, Somat, Calgonit',
  'Haushalt & Reinigung|Reiniger': 'Meister Proper, Sagrotan, Frosch, Cillit Bang, Domestos, Viss, Der General, Antikal, WC-Ente, Harpic',
  'Haushalt & Reinigung|Toilettenpapier & Küchenrolle': 'Zewa, Hakle, Cottonelle, Tempo, Charmin, Plenty',
  'Haushalt & Reinigung|Folien & Beutel': 'Toppits, Swirl, Melitta',
  'Haushalt & Reinigung|Batterien & Leuchtmittel': 'Varta, Duracell, Energizer, Philips, Osram',

  // Tierbedarf
  'Tierbedarf|Katzenfutter': 'Whiskas, Felix, Sheba, Gourmet, Kitekat, Miamor, Catsan, Dreamies',
  'Tierbedarf|Katzenstreu': 'Catsan, Cat\'s Best, Biokat\'s',
  'Tierbedarf|Hundefutter': 'Pedigree, Chappi, Cesar, Frolic, Rinti, Butcher\'s, Purina',
};

/* Bekannte Eigenmarken der Händler: [Name, Händler, wo sie vorkommen]. „wo“: Kategorien oder „Kategorie/Gruppe“,
   kommagetrennt; „Lebensmittel“ = alle Lebensmittel-Kategorien (breit aufgestellte Marken wie ja! oder Gut & Günstig). */
const KNOWN_OWN = [
  // Lidl
  ['Milbona', 'lidl', 'Milch & Molkerei, Käse'],
  ['Pilos', 'lidl', 'Milch & Molkerei, Käse'],
  ['Choceur', 'lidl', 'Süßes & Snacks/Schokolade, Süßes & Snacks/Riegel, Süßes & Snacks/Pralinen, Süßes & Snacks/Weihnachtssüßes'],
  ['Favorina', 'lidl', 'Süßes & Snacks/Weihnachtssüßes, Süßes & Snacks/Pralinen'],
  ['Sondey', 'lidl', 'Süßes & Snacks/Kekse & Waffeln, Süßes & Snacks/Riegel'],
  ['Snack Day', 'lidl', 'Süßes & Snacks/Chips & Knabbereien'],
  ['Alesto', 'lidl', 'Süßes & Snacks/Nüsse & Trockenfrüchte'],
  ['Crownfield', 'lidl', 'Frühstück & Aufstrich/Müsli & Cerealien, Frühstück & Aufstrich/Haferflocken & Porridge'],
  ['Bellarom', 'lidl', 'Kaffee & Tee'],
  ['Freeway', 'lidl', 'Getränke'],
  ['Saskia', 'lidl', 'Getränke/Wasser'],
  ['Solevita', 'lidl', 'Getränke/Saft & Nektar'],
  ['Perlenbacher', 'lidl', 'Bier'],
  ['Combino', 'lidl', 'Vorrat & Konserven/Nudeln, Vorrat & Konserven/Soßen & Pesto'],
  ['Italiamo', 'lidl', 'Vorrat & Konserven, Käse, Tiefkühl, Wurst & Aufschnitt'],
  ['Chef Select', 'lidl', 'Vorrat & Konserven/Fertiggerichte, Vorrat & Konserven/Suppen & Eintöpfe, Tiefkühl, Fleisch & Geflügel'],
  ['Kania', 'lidl', 'Vorrat & Konserven/Gewürze, Vorrat & Konserven/Ketchup, Senf & Mayo, Vorrat & Konserven/Soßen & Pesto'],
  ['Vitasia', 'lidl', 'Vorrat & Konserven'],
  ['Belbake', 'lidl', 'Vorrat & Konserven/Mehl, Zucker & Backen'],
  ['Dulano', 'lidl', 'Wurst & Aufschnitt'],
  ['Metzgerfrisch', 'lidl', 'Fleisch & Geflügel'],
  ['Golden Seafood', 'lidl', 'Fisch & Meeresfrüchte, Tiefkühl/TK-Fisch'],
  ['Nautica', 'lidl', 'Fisch & Meeresfrüchte'],
  ['Eridanous', 'lidl', 'Käse/Feta & Hirtenkäse, Vorrat & Konserven, Süßes & Snacks'],
  ['Gelatelli', 'lidl', 'Tiefkühl/Eis'],
  ['Trattoria Alfredo', 'lidl', 'Tiefkühl/Pizza & Baguettes'],
  ['Vemondo', 'lidl', 'Milch & Molkerei/Pflanzendrinks, Fleisch & Geflügel/Burger & Frikadellen, Käse/Käsealternativen'],
  ['Next Level', 'lidl', 'Fleisch & Geflügel/Burger & Frikadellen, Fleisch & Geflügel/Hackfleisch'],
  ['Deluxe', 'lidl', 'Lebensmittel'],
  ['Cien', 'lidl', 'Drogerie & Pflege'],
  ['Formil', 'lidl', 'Haushalt & Reinigung/Waschmittel, Haushalt & Reinigung/Weichspüler & Wäschepflege'],
  ['W5', 'lidl', 'Haushalt & Reinigung'],
  ['Lupilu', 'lidl', 'Baby & Kind'],
  ['Coshida', 'lidl', 'Tierbedarf/Katzenfutter'],
  ['Orlando', 'lidl', 'Tierbedarf/Hundefutter'],
  // Aldi
  ['Milsani', 'aldi', 'Milch & Molkerei, Käse'],
  ['Moser Roth', 'aldi', 'Süßes & Snacks/Schokolade, Süßes & Snacks/Pralinen, Süßes & Snacks/Weihnachtssüßes'],
  ['Knusperone', 'aldi', 'Frühstück & Aufstrich/Müsli & Cerealien'],
  ['Barissimo', 'aldi', 'Kaffee & Tee'],
  ['River', 'aldi', 'Getränke/Cola, Getränke/Limonade & Schorle'],
  ['Rio d\'Oro', 'aldi', 'Getränke/Saft & Nektar'],
  ['Bon Gelati', 'aldi', 'Tiefkühl/Eis'],
  ['Cucina Nobile', 'aldi', 'Vorrat & Konserven'],
  ['Mühlengold', 'aldi', 'Brot & Backwaren, Vorrat & Konserven/Mehl, Zucker & Backen'],
  ['Wonnemeyer', 'aldi', 'Wurst & Aufschnitt'],
  ['Meine Metzgerei', 'aldi', 'Fleisch & Geflügel'],
  ['Almare', 'aldi', 'Fisch & Meeresfrüchte, Tiefkühl/TK-Fisch'],
  ['Mein Bestes', 'aldi', 'Lebensmittel'],
  ['Tandil', 'aldi', 'Haushalt & Reinigung/Waschmittel, Haushalt & Reinigung/Weichspüler & Wäschepflege'],
  ['Kokett', 'aldi', 'Haushalt & Reinigung/Toilettenpapier & Küchenrolle, Drogerie & Pflege/Hygiene'],
  ['Lacura', 'aldi', 'Drogerie & Pflege'],
  ['Mamia', 'aldi', 'Baby & Kind'],
  ['Cachet', 'aldi', 'Tierbedarf/Katzenfutter'],
  ['Romeo', 'aldi', 'Tierbedarf/Hundefutter'],
  // Edeka
  ['Gut & Günstig', 'edeka', 'Lebensmittel, Haushalt & Reinigung, Drogerie & Pflege'],
  ['Edeka Bio', 'edeka', 'Lebensmittel'],
  ['Edeka Herzstücke', 'edeka', 'Lebensmittel'],
  ['Edeka Italia', 'edeka', 'Vorrat & Konserven, Käse, Wurst & Aufschnitt, Tiefkühl'],
  ['Edeka Genussmomente', 'edeka', 'Lebensmittel'],
  ['Edeka zuhause', 'edeka', 'Haushalt & Reinigung'],
  ['Elkos', 'edeka', 'Drogerie & Pflege'],
  ['Gutes Land', 'edeka', 'Fleisch & Geflügel, Wurst & Aufschnitt'],
  // Rewe, Penny
  ['ja!', 'rewe', 'Lebensmittel, Haushalt & Reinigung, Drogerie & Pflege, Tierbedarf'],
  ['Rewe Beste Wahl', 'rewe', 'Lebensmittel'],
  ['Rewe Bio', 'rewe', 'Lebensmittel'],
  ['Rewe Feine Welt', 'rewe', 'Lebensmittel'],
  ['Rewe Regional', 'rewe', 'Lebensmittel'],
  ['Penny Ready', 'penny', 'Vorrat & Konserven/Fertiggerichte, Tiefkühl/TK-Fertiggerichte'],
  ['Food for Future', 'penny', 'Fleisch & Geflügel/Burger & Frikadellen, Milch & Molkerei/Pflanzendrinks, Käse/Käsealternativen'],
  ['Naturgut', 'penny', 'Lebensmittel'],
  ['Mühlenhof', 'penny', 'Fleisch & Geflügel, Wurst & Aufschnitt'],
  // Netto
  ['BioBio', 'netto', 'Lebensmittel'],
  ['Jeden Tag', 'netto', 'Lebensmittel'],
  ['Gut Bio', 'netto', 'Lebensmittel'],
  // Rossmann
  ['Isana', 'rossmann', 'Drogerie & Pflege'],
  ['Alterra', 'rossmann', 'Drogerie & Pflege'],
  ['Babydream', 'rossmann', 'Baby & Kind'],
  ['Domol', 'rossmann', 'Haushalt & Reinigung'],
  ['Prokudent', 'rossmann', 'Drogerie & Pflege/Zahnpflege'],
  ['Altapharma', 'rossmann', 'Drogerie & Pflege/Gesundheit & Vitamine'],
  ['Facelle', 'rossmann', 'Drogerie & Pflege/Hygiene'],
  ['Enerbio', 'rossmann', 'Lebensmittel'],
];
